import type { CategoriaSeed, InterventoSeed, SettoreSeed } from './seed-types'

type SettoreData = Omit<SettoreSeed, 'categorie'>

type CategoriaData = CategoriaSeed & {
  settoreSlug: string
}

/**
 * Settori = solo contenitori editoriali/navigazionali.
 * Non guidano il matching cliente.
 */
export const settoriData: SettoreData[] = [
  {
    nome: 'Edilizia e ristrutturazioni',
    slug: 'edilizia-e-ristrutturazioni',
    descrizione:
      'Lavori edili, ristrutturazioni complete e parziali, muratura, cappotti e interventi strutturali.',
    fase: 'CORE',
    ordine: 1,
  },
  {
    nome: 'Impianti',
    slug: 'impianti',
    descrizione:
      'Installazione, riparazione e manutenzione di impianti idraulici, elettrici, termici e climatici.',
    fase: 'CORE',
    ordine: 2,
  },
  {
    nome: 'Finiture e interni',
    slug: 'finiture-e-interni',
    descrizione:
      'Tinteggiatura, pavimentazione, piastrelle, falegnameria, vetri e infissi per interni.',
    fase: 'CORE',
    ordine: 3,
  },
  {
    nome: 'Esterni e pertinenze',
    slug: 'esterni-e-pertinenze',
    descrizione: "Coperture, giardini, recinzioni e lavori esterni all'abitazione.",
    fase: 'CORE',
    ordine: 4,
  },
  {
    nome: 'Manutenzione rapida',
    slug: 'manutenzione-rapida',
    descrizione:
      'Piccole riparazioni domestiche, disinfestazione, pulizie professionali e interventi veloci.',
    fase: 'CORE',
    ordine: 5,
  },
  {
    nome: 'Progettazione tecnica',
    slug: 'progettazione-tecnica',
    descrizione: 'Progettazione, pratiche edilizie, perizie e direzione lavori.',
    fase: 'ADJACENT',
    ordine: 6,
  },
  {
    nome: 'Interior e valorizzazione casa',
    slug: 'interior-e-valorizzazione-casa',
    descrizione:
      'Consulenza arredamento, home staging e valorizzazione estetica degli spazi.',
    fase: 'ADJACENT',
    ordine: 7,
  },
  {
    nome: 'Traslochi e sgomberi',
    slug: 'traslochi-e-sgomberi',
    descrizione:
      'Traslochi residenziali e commerciali, sgomberi e smaltimento mobili.',
    fase: 'ADJACENT',
    ordine: 8,
  },
]

/**
 * Categorie = unità operative reali.
 * Una categoria è un tipo di fornitore/professionista.
 *
 * Nota:
 * - il professionista seleziona una o più categorie
 * - poi seleziona i servizi che offre davvero
 * - il settore serve solo a raggruppare
 */
export const categorieData: CategoriaData[] = [

  {
    settoreSlug: 'finiture-e-interni',
    nome: 'Serramentista e vetraio',
    slug: 'serramentista-vetraio',
    descrizione:
      'Specialista in vetri, finestre, infissi, serramenti, zanzariere, tapparelle e regolazioni di porte finestre.',
    alias: ['vetraio', 'tecnico infissi', 'serramentista', 'tecnico serramenti'],
    searchTerms: [
      'vetraio',
      'serramentista',
      'vetro rotto',
      'finestre',
      'infissi',
      'doppio vetro',
      'vetrocamera',
      'serramenti',
      'zanzariere',
      'tapparelle',
      'porta finestra',
    ],
    servizi: [
      'Sostituzione vetro rotto',
      'Sostituzione vetrocamera',
      'Installazione finestre',
      'Installazione infissi',
      'Riparazione serramenti',
      'Regolazione finestre e porte finestre',
      'Installazione zanzariere',
      'Sostituzione tapparelle',
      'Riparazione tapparelle',
      'Manutenzione serramenti',
    ],
  },
  {
    settoreSlug: 'impianti',
    nome: 'Idraulico',
    slug: 'idraulico',
    descrizione:
      'Specialista in impianti idraulici, perdite d’acqua, scarichi, rubinetti, sanitari, box doccia e collegamenti domestici.',
    alias: ['impiantista idraulico', 'tecnico idraulico'],
    searchTerms: [
      'idraulico',
      'perdita acqua',
      'perdita idrica',
      'rubinetto',
      'sanitari',
      'scarico intasato',
      'impianto idraulico',
      'scaldacqua',
      'boiler',
      'box doccia',
      'lavatrice',
      'lavastoviglie',
    ],
    servizi: [
      'Sostituzione rubinetto',
      'Riparazione perdita acqua',
      'Installazione sanitari',
      'Sostituzione boiler o scaldacqua',
      'Installazione impianto idraulico',
      'Scarichi intasati',
      'Riparazione scarico wc',
      'Installazione box doccia',
      'Sostituzione vasca o doccia',
      'Installazione lavatrice o lavastoviglie',
    ],
  },
  {
    settoreSlug: 'esterni-e-pertinenze',
    nome: 'Fabbro',
    slug: 'fabbro',
    descrizione:
      'Specialista in serrature, cancelli, inferriate, recinzioni, ringhiere, parapetti e lavorazioni metalliche.',
    alias: ['carpentiere ferro', 'tecnico serrature', 'tecnico automazioni cancello'],
    searchTerms: [
      'fabbro',
      'serratura',
      'cancello',
      'cancello automatico',
      'inferriate',
      'ringhiere',
      'parapetti',
      'recinzione',
      'ferro',
      'carpenteria metallica',
    ],
    servizi: [
      'Sostituzione serratura',
      'Riparazione serratura',
      'Apertura porta bloccata',
      'Installazione cancello',
      'Riparazione cancello automatico',
      'Installazione inferriate',
      'Installazione recinzione',
      'Riparazione ringhiere e parapetti',
      'Realizzazione ringhiere e parapetti',
      'Piccole lavorazioni in ferro',
    ],
  },
  {
  settoreSlug: 'esterni-e-pertinenze',
  nome: 'Impresa piscine',
  slug: 'impresa-piscine',
  descrizione:
    'Impresa specializzata nella realizzazione, ristrutturazione e manutenzione di piscine private.',
  alias: ['piscinista', 'azienda piscine', 'costruttore piscine'],
  searchTerms: [
    'piscine',
    'piscinista',
    'realizzazione piscina',
    'costruzione piscina',
    'manutenzione piscina',
  ],
  servizi: [
    'Realizzazione piscine interrate',
    'Realizzazione piscine fuori terra',
    'Ristrutturazione piscina',
    'Manutenzione piscina',
    'Riparazione piscina',
    'Installazione impianto filtrazione piscina',
  ],
  },

  {
  settoreSlug: 'edilizia-e-ristrutturazioni',
  nome: 'Muratore',
  slug: 'muratore',
  descrizione:
    'Specialista in opere murarie, piccola muratura, tramezzi, demolizioni leggere, riparazioni muri, aperture e ripristini localizzati.',
  alias: ['muratore edile', 'manutenzione muratura', 'operaio edile'],
  searchTerms: [
    'muratore',
    'muratura',
    'piccola muratura',
    'riparazione muri',
    'muro',
    'crepe muro',
    'tramezzo',
    'demolizione muro',
    'apertura porta muro',
    'intonaco',
    'rasatura',
  ],
  servizi: [
    'Piccola muratura',
    'Riparazione crepe e lesioni',
    'Demolizioni e rimozioni leggere',
    'Costruzione muri e tramezze',
    'Apertura vani porta e finestra',
    'Chiusura aperture',
    'Intonaci e rasature',
    'Posa mattoni e blocchi',
    'Ripristino frontalini',
  ],
},
{
  settoreSlug: 'finiture-e-interni',
  nome: 'Cartongessista',
  slug: 'cartongessista',
  descrizione:
    'Specialista in pareti, contropareti, controsoffitti, velette, abbassamenti e riparazioni in cartongesso.',
  alias: ['tecnico cartongesso', 'posatore cartongesso', 'artigiano cartongesso'],
  searchTerms: [
    'cartongessista',
    'cartongesso',
    'parete in cartongesso',
    'controsoffitto',
    'controsoffitto cartongesso',
    'veletta cartongesso',
    'abbassamento soffitto',
    'controparete',
  ],
  servizi: [
    'Pareti in cartongesso',
    'Controsoffitti in cartongesso',
    'Contropareti in cartongesso',
    'Velette e abbassamenti',
    'Riparazioni cartongesso',
  ],
},
{
  settoreSlug: 'impianti',
  nome: 'Elettricista',
  slug: 'elettricista',
  descrizione:
    'Specialista in impianti elettrici, prese, interruttori, quadri elettrici, punti luce, messa a norma e wallbox.',
  alias: ['impiantista elettrico', 'tecnico elettrico'],
  searchTerms: [
    'elettricista',
    'impianto elettrico',
    'presa elettrica',
    'interruttore',
    'quadro elettrico',
    'messa a norma',
    'punti luce',
    'wallbox',
    'salvavita',
    'corto circuito',
  ],
  servizi: [
    'Sostituzione prese e interruttori',
    'Installazione impianto elettrico',
    'Messa a norma impianto elettrico',
    'Installazione quadro elettrico',
    'Installazione punti luce',
    'Riparazione guasto elettrico',
    'Installazione salvavita',
    'Installazione wallbox',
  ],
},

{
  settoreSlug: 'finiture-e-interni',
  nome: 'Imbianchino',
  slug: 'imbianchino',
  descrizione:
    'Specialista in tinteggiatura interna ed esterna, soffitti, decorazioni, carta da parati e finiture pittoriche.',
  alias: ['pittore', 'tinteggiatore', 'verniciatore interni'],
  searchTerms: [
    'imbianchino',
    'tinteggiatura',
    'imbiancare',
    'pittura interni',
    'verniciare pareti',
    'tinteggiare casa',
    'soffitti',
    'carta da parati',
  ],
  servizi: [
    'Tinteggiatura pareti interne',
    'Tinteggiatura soffitti',
    'Tinteggiatura facciata',
    'Decorazione pareti',
    'Applicazione carta da parati',
    'Rimozione carta da parati',
  ],
},
{
  settoreSlug: 'finiture-e-interni',
  nome: 'Piastrellista',
  slug: 'piastrellista',
  descrizione:
    'Specialista in posa e riparazione di piastrelle, rivestimenti bagno, rivestimenti cucina, fughe e superfici ceramiche.',
  alias: ['posatore piastrelle', 'rivestimentista'],
  searchTerms: [
    'piastrellista',
    'piastrelle',
    'posa piastrelle',
    'rivestimento bagno',
    'rivestimento cucina',
    'fughe',
    'gres',
    'ceramica',
  ],
  servizi: [
    'Posa piastrelle bagno',
    'Posa piastrelle cucina',
    'Posa rivestimenti',
    'Riparazione fughe e piastrelle',
    'Sostituzione piastrelle rotte',
  ],
},
{
  settoreSlug: 'finiture-e-interni',
  nome: 'Pavimentista',
  slug: 'pavimentista',
  descrizione:
    'Specialista in posa e riparazione di pavimenti in gres, parquet, resina e pavimentazioni interne o esterne.',
  alias: ['posatore pavimenti', 'tecnico pavimentazioni'],
  searchTerms: [
    'pavimentista',
    'posa pavimento',
    'parquet',
    'gres',
    'resina',
    'pavimento',
    'pavimento esterno',
    'levigatura parquet',
  ],
  servizi: [
    'Posa pavimento in gres',
    'Posa parquet',
    'Posa pavimento in resina',
    'Riparazione pavimento',
    'Levigatura parquet',
    'Posa pavimento esterno',
  ],
},
{
  settoreSlug: 'finiture-e-interni',
  nome: 'Falegname',
  slug: 'falegname',
  descrizione:
    'Specialista in lavorazioni in legno, porte interne, mobili su misura, riparazioni mobili e arredi.',
  alias: ['ebanista', 'mobiliere', 'carpentiere legno'],
  searchTerms: [
    'falegname',
    'porta interna',
    'mobili su misura',
    'armadio',
    'legno',
    'riparazione mobili',
    'armadio a muro',
  ],
  servizi: [
    'Installazione porte interne',
    'Riparazione mobili',
    'Realizzazione mobili su misura',
    'Installazione armadio a muro',
    'Riparazione porte interne',
  ],
},
{
  settoreSlug: 'esterni-e-pertinenze',
  nome: 'Giardiniere',
  slug: 'giardiniere',
  descrizione:
    'Specialista nella cura, manutenzione e progettazione di giardini, potature, siepi, prato e irrigazione.',
  alias: ['giardinaggio', 'manutentore verde', 'paesaggista'],
  searchTerms: [
    'giardiniere',
    'giardino',
    'potatura',
    'siepe',
    'erba',
    'irrigazione',
    'prato',
    'alberi',
    'manutenzione verde',
  ],
  servizi: [
    'Potatura piante e siepi',
    'Manutenzione giardino',
    'Progettazione giardino',
    'Rimozione alberi',
    'Irrigazione automatica',
    'Taglio prato',
    'Semina prato',
  ],
},
{
  settoreSlug: 'impianti',
  nome: 'Antennista',
  slug: 'antennista',
  descrizione:
    'Specialista in installazione, regolazione e riparazione di antenne TV, impianti satellitari e sistemi di ricezione.',
  alias: ['tecnico antenna', 'impiantista TV'],
  searchTerms: [
    'antennista',
    'antenna TV',
    'satellite',
    'decoder',
    'impianto televisivo',
    'segnale TV',
    'parabola',
  ],
  servizi: [
    'Installazione antenna TV',
    'Installazione antenna satellitare',
    'Riparazione impianto TV',
    'Regolazione antenna TV',
    'Installazione presa antenna',
  ],
},
{
  settoreSlug: 'manutenzione-rapida',
  nome: 'Disinfestatore',
  slug: 'disinfestatore',
  descrizione:
    'Specialista in trattamenti professionali contro insetti, roditori, parassiti, blatte, formiche, zanzare e tarme.',
  alias: ['derattizzatore', 'tecnico disinfestazione'],
  searchTerms: [
    'disinfestatore',
    'disinfestazione',
    'topi',
    'blatte',
    'formiche',
    'zanzare',
    'roditori',
    'tarme',
    'insetti infestanti',
  ],
  servizi: [
    'Disinfestazione insetti',
    'Derattizzazione',
    'Trattamento tarme',
    'Disinfestazione blatte',
    'Disinfestazione formiche',
    'Trattamento zanzare',
  ],
},
{
  settoreSlug: 'manutenzione-rapida',
  nome: 'Pulitore professionale',
  slug: 'pulitore-professionale',
  descrizione:
    'Professionista o impresa specializzata in pulizie straordinarie, fine cantiere, vetri, facciate, tappeti, divani e ambienti dopo lavori.',
  alias: ['addetto pulizie', 'impresa pulizie', 'impresa di pulizia'],
  searchTerms: [
    'pulizie professionali',
    'pulizia appartamento',
    'pulizia fine cantiere',
    'pulizia dopo lavori',
    'tappeti',
    'divano',
    'vetri',
    'facciate',
  ],
  servizi: [
    'Pulizia fine cantiere',
    'Pulizia straordinaria appartamento',
    'Lavaggio tappeti e divani',
    'Pulizia vetri e facciate',
    'Pulizia post ristrutturazione',
  ],
},
{
  settoreSlug: 'traslochi-e-sgomberi',
  nome: 'Traslocatore',
  slug: 'traslocatore',
  descrizione:
    'Professionista o impresa specializzata in traslochi, sgomberi, smontaggio mobili, rimontaggio mobili e smaltimento arredi.',
  alias: ['impresa traslochi', 'azienda traslochi', 'sgomberi'],
  searchTerms: [
    'traslocatore',
    'trasloco',
    'sgombero',
    'smontaggio mobili',
    'imballaggio',
    'trasloco appartamento',
    'trasloco ufficio',
    'smaltimento mobili',
  ],
  servizi: [
    'Trasloco appartamento',
    'Trasloco ufficio',
    'Sgombero appartamento',
    'Smaltimento mobili',
    'Montaggio e smontaggio mobili',
    'Imballaggio mobili',
  ],
},
{
  settoreSlug: 'esterni-e-pertinenze',
  nome: 'Impresa coperture',
  slug: 'impresa-coperture',
  descrizione:
    'Impresa specializzata in rifacimento e riparazione tetti, terrazzi, grondaie e impermeabilizzazioni esterne.',
  alias: ['copritetto', 'impresa tetti', 'impresa impermeabilizzazioni'],
  searchTerms: [
    'coperture',
    'tetto',
    'rifacimento tetto',
    'riparazione tetto',
    'terrazza',
    'infiltrazione',
    'grondaie',
    'impermeabilizzazione terrazzo',
  ],
  servizi: [
    'Rifacimento tetto',
    'Riparazione tetto',
    'Installazione grondaie',
    'Impermeabilizzazione terrazzo',
    'Rifacimento terrazza',
    'Riparazione grondaie',
  ],
}
,
{
  settoreSlug: 'edilizia-e-ristrutturazioni',
  nome: 'Impresa edile e ristrutturazioni',
  slug: 'impresa-edile',
  descrizione:
    'Impresa che gestisce lavori edili, ristrutturazioni parziali o complete, demolizioni, murature, facciate, balconi, cappotti e lavori chiavi in mano.',
  alias: [
    'impresa edile',
    'impresa ristrutturazioni',
    'ditta edile',
    'ditta ristrutturazioni',
    'impresa costruzioni',
    'general contractor',
    'chiavi in mano',
  ],
  searchTerms: [
    'impresa edile',
    'ristrutturazioni',
    'ditta ristrutturazioni',
    'lavori edili',
    'impresa costruzioni',
    'ristrutturazione casa',
    'ristrutturazione appartamento',
    'rifacimento bagno',
    'rifacimento cucina',
    'chiavi in mano',
    'facciata',
    'cappotto termico',
    'balconi',
  ],
  servizi: [
    'Ristrutturazione appartamento',
    'Ristrutturazione bagno chiavi in mano',
    'Ristrutturazione cucina chiavi in mano',
    'Coordinamento lavori edili',
    'Demolizioni e rimozioni',
    'Costruzione muri e tramezze',
    'Rifacimento balconi',
    'Rifacimento facciata',
    'Rifacimento solaio',
    'Cappotto termico',
    'Intonaci e rasature',
    'Impermeabilizzazione facciata',
  ],
},
{
  settoreSlug: 'manutenzione-rapida',
  nome: 'Tuttofare',
  slug: 'tuttofare',
  descrizione:
    'Professionista per piccole riparazioni domestiche, montaggi, fissaggi, sigillature e interventi rapidi di manutenzione ordinaria.',
  alias: ['factotum', 'manutentore domestico', 'handyman'],
  searchTerms: [
    'tuttofare',
    'handyman',
    'piccole riparazioni',
    'montaggio mobili',
    'ikea',
    'mensola',
    'quadri',
    'sigillatura',
    'piccola manutenzione',
  ],
  servizi: [
    'Montaggio mobili',
    'Montaggio mobili IKEA',
    'Appendere quadri e mensole',
    'Piccole riparazioni domestiche',
    'Sigillatura e stuccatura',
    'Sostituzione lampadine e plafoniere',
    'Piccoli fissaggi domestici',
    'Regolazione ante e cerniere',
  ],
},
{
  settoreSlug: 'progettazione-tecnica',
  nome: 'Geometra',
  slug: 'geometra',
  descrizione:
    'Tecnico per pratiche catastali, rilievi metrici, pratiche edilizie, perizie, direzione lavori e supporto tecnico alla ristrutturazione.',
  alias: ['tecnico geometra', 'consulente pratiche edilizie'],
  searchTerms: [
    'geometra',
    'pratica catastale',
    'catasto',
    'cila',
    'cilas',
    'scia',
    'rilievo',
    'perizia immobiliare',
    'direzione lavori',
    'pratiche edilizie',
  ],
  servizi: [
    'Pratica catastale',
    'Rilievo metrico',
    'Perizia immobiliare',
    'Direzione lavori',
    'Pratica CILA',
    'Pratica SCIA',
    'Pratica CILAS',
    'Variazione catastale',
  ],
},
{
  settoreSlug: 'progettazione-tecnica',
  nome: 'Architetto',
  slug: 'architetto',
  descrizione:
    'Professionista per progettazione architettonica, ristrutturazioni, distribuzione spazi, interior design, ampliamenti e pratiche urbanistiche.',
  alias: ['studio architettura', 'progettista', 'architetto casa'],
  searchTerms: [
    'architetto',
    'progetto ristrutturazione',
    'progettazione casa',
    'interior design',
    'permesso costruire',
    'ampliamento casa',
    'distribuzione spazi',
    'progetto casa',
  ],
  servizi: [
    'Progetto ristrutturazione',
    'Interior design',
    'Progetto ampliamento',
    'Progetto nuova costruzione',
    'Permesso di costruire',
    'Distribuzione spazi interni',
    'Scelta materiali e finiture',
  ],
},
{
  settoreSlug: 'progettazione-tecnica',
  nome: 'Ingegnere',
  slug: 'ingegnere',
  descrizione:
    'Tecnico per perizie strutturali, certificazioni energetiche, progettazione impianti, verifiche sismiche e relazioni tecniche.',
  alias: ['ingegnere civile', 'ingegnere strutturale', 'perito industriale'],
  searchTerms: [
    'ingegnere',
    'ingegnere civile',
    'ingegnere strutturale',
    'perizia strutturale',
    'ape',
    'certificazione energetica',
    'sismica',
    'progetto impianti',
    'relazione tecnica',
  ],
  servizi: [
    'Perizia strutturale',
    'Certificazione energetica APE',
    'Progetto impianti',
    'Relazione tecnica sismica',
    'Verifica strutturale',
    'Calcolo strutturale',
  ],
},
{
  settoreSlug: 'interior-e-valorizzazione-casa',
  nome: 'Interior designer',
  slug: 'interior-designer',
  descrizione:
    'Professionista per consulenza arredamento, progettazione degli spazi interni, home staging, illuminazione e valorizzazione estetica della casa.',
  alias: ['decoratore interni', 'consulente arredamento', 'home stager'],
  searchTerms: [
    'interior designer',
    'arredamento',
    'consulenza arredamento',
    'home staging',
    'illuminazione',
    'restyling casa',
    'scelta materiali',
    'decorazione interni',
  ],
  servizi: [
    'Consulenza arredamento',
    'Home staging',
    'Progetto illuminazione',
    'Scelta materiali e finiture',
    'Restyling casa',
    'Progetto arredo interni',
  ],
}
,
{
  settoreSlug: 'impianti',
  nome: 'Termoidraulico',
  slug: 'termoidraulico',
  descrizione:
    'Specialista in caldaie, riscaldamento, radiatori, pompe di calore, climatizzatori e impianti termici.',
  alias: ['termotecnico', 'impiantista termico', 'tecnico caldaie', 'tecnico climatizzatori'],
  searchTerms: [
    'termoidraulico',
    'caldaia',
    'riscaldamento',
    'radiatori',
    'termosifoni',
    'climatizzatore',
    'condizionatore',
    'pompa di calore',
    'riscaldamento a pavimento',
    'impianto termico',
  ],
  servizi: [
    'Installazione caldaia',
    'Manutenzione caldaia',
    'Riparazione caldaia',
    'Sostituzione radiatori',
    'Installazione pompa di calore',
    'Installazione riscaldamento a pavimento',
    'Installazione climatizzatore',
    'Manutenzione climatizzatore',
    'Riparazione climatizzatore',
  ],
},
]

export const interventiData: InterventoSeed[] = [
    
{
  nome: 'Installazione caldaia',
  slug: 'installazione-caldaia',
  descrizione:
    'Installazione o sostituzione di una caldaia con collegamenti e messa in funzione.',
  alias: ['cambio caldaia', 'caldaia nuova', 'montaggio caldaia', 'sostituzione caldaia'],
  searchTerms: [
    'installazione caldaia',
    'sostituzione caldaia',
    'caldaia nuova',
    'montaggio caldaia',
    'cambio caldaia',
  ],
  ordine: 17,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Installazione caldaia' }],
},
{
  nome: 'Installazione climatizzatore',
  slug: 'installazione-climatizzatore',
  descrizione:
    'Installazione di un climatizzatore o condizionatore con predisposizioni e collegamenti tecnici.',
  alias: ['montaggio condizionatore', 'installare condizionatore', 'aria condizionata nuova'],
  searchTerms: [
    'installazione climatizzatore',
    'montaggio condizionatore',
    'installare condizionatore',
    'installazione condizionatore',
    'aria condizionata nuova',
  ],
  ordine: 18,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Installazione climatizzatore' }],
},
{
  nome: 'Manutenzione caldaia',
  slug: 'manutenzione-caldaia',
  descrizione:
    'Manutenzione ordinaria, controllo, pulizia e verifica della caldaia.',
  alias: ['controllo caldaia', 'pulizia caldaia', 'revisione caldaia', 'bollino caldaia'],
  searchTerms: [
    'manutenzione caldaia',
    'controllo caldaia',
    'pulizia caldaia',
    'revisione caldaia',
    'bollino caldaia',
  ],
  ordine: 50,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Manutenzione caldaia' }],
},
{
  nome: 'Riparazione caldaia',
  slug: 'riparazione-caldaia',
  descrizione:
    'Riparazione di guasti o malfunzionamenti della caldaia.',
  alias: ['caldaia rotta', 'guasto caldaia', 'caldaia non parte', 'caldaia in blocco'],
  searchTerms: [
    'riparazione caldaia',
    'caldaia rotta',
    'guasto caldaia',
    'caldaia non parte',
    'caldaia in blocco',
  ],
  ordine: 51,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Riparazione caldaia' }],
},
{
  nome: 'Sostituzione radiatori',
  slug: 'sostituzione-radiatori',
  descrizione:
    'Sostituzione o installazione di radiatori, termosifoni e collegamenti al riscaldamento.',
  alias: ['cambio radiatori', 'sostituzione termosifoni', 'radiatori nuovi'],
  searchTerms: [
    'sostituzione radiatori',
    'cambio radiatori',
    'sostituzione termosifoni',
    'radiatori nuovi',
    'termosifoni nuovi',
  ],
  ordine: 84,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Sostituzione radiatori' }],
},
{
  nome: 'Installazione pompa di calore',
  slug: 'installazione-pompa-di-calore',
  descrizione:
    'Installazione o sostituzione di pompa di calore per riscaldamento, raffrescamento o acqua calda.',
  alias: ['pompa di calore nuova', 'montaggio pompa di calore', 'sostituzione pompa di calore'],
  searchTerms: [
    'installazione pompa di calore',
    'pompa di calore nuova',
    'montaggio pompa di calore',
    'sostituzione pompa di calore',
  ],
  ordine: 85,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Installazione pompa di calore' }],
},
{
  nome: 'Installazione riscaldamento a pavimento',
  slug: 'installazione-riscaldamento-a-pavimento',
  descrizione:
    'Installazione di impianto di riscaldamento a pavimento per abitazioni o locali interni.',
  alias: ['riscaldamento a pavimento', 'impianto radiante', 'pavimento radiante'],
  searchTerms: [
    'installazione riscaldamento a pavimento',
    'riscaldamento a pavimento',
    'impianto radiante',
    'pavimento radiante',
  ],
  ordine: 86,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Installazione riscaldamento a pavimento' }],
},
{
  nome: 'Manutenzione climatizzatore',
  slug: 'manutenzione-climatizzatore',
  descrizione:
    'Pulizia, controllo e manutenzione ordinaria di climatizzatori e condizionatori.',
  alias: ['pulizia climatizzatore', 'pulizia condizionatore', 'manutenzione condizionatore'],
  searchTerms: [
    'manutenzione climatizzatore',
    'pulizia climatizzatore',
    'pulizia condizionatore',
    'manutenzione condizionatore',
  ],
  ordine: 87,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Manutenzione climatizzatore' }],
},
{
  nome: 'Riparazione climatizzatore',
  slug: 'riparazione-climatizzatore',
  descrizione:
    'Riparazione di climatizzatori o condizionatori che non raffreddano, perdono acqua o non si accendono.',
  alias: ['climatizzatore rotto', 'condizionatore rotto', 'condizionatore non raffredda'],
  searchTerms: [
    'riparazione climatizzatore',
    'climatizzatore rotto',
    'condizionatore rotto',
    'condizionatore non raffredda',
    'condizionatore perde acqua',
  ],
  ordine: 88,
  categorie: [{ slug: 'termoidraulico', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'termoidraulico', nome: 'Riparazione climatizzatore' }],
},
    
{
  nome: 'Ristrutturazione casa',
  slug: 'ristrutturazione-casa',
  descrizione:
    'Ristrutturazione completa o estesa della casa con più lavorazioni coordinate e gestione chiavi in mano.',
  alias: ['rifare casa', 'ristrutturare casa', 'ristrutturazione completa casa'],
  searchTerms: [
    'ristrutturazione casa',
    'rifare casa',
    'ristrutturare casa',
    'lavori casa completi',
    'ristrutturare abitazione',
    'ristrutturazione chiavi in mano',
  ],
  ordine: 1,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Ristrutturazione appartamento' },
    { catSlug: 'impresa-edile', nome: 'Coordinamento lavori edili' },
  ],
},
{
  nome: 'Rifacimento bagno',
  slug: 'rifacimento-bagno',
  descrizione:
    'Rifacimento completo del bagno con demolizioni, impianti, rivestimenti, sanitari e finiture.',
  alias: ['ristrutturazione bagno', 'bagno nuovo', 'rifare bagno'],
  searchTerms: [
    'rifacimento bagno',
    'ristrutturazione bagno',
    'bagno nuovo',
    'rifare bagno',
    'bagno da rifare',
    'bagno chiavi in mano',
  ],
  ordine: 4,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Ristrutturazione bagno chiavi in mano' },
    { catSlug: 'impresa-edile', nome: 'Demolizioni e rimozioni' },
    { catSlug: 'impresa-edile', nome: 'Coordinamento lavori edili' },
  ],
},
{
  nome: 'Rifacimento cucina',
  slug: 'rifacimento-cucina',
  descrizione:
    'Rifacimento completo della cucina con impianti, rivestimenti, finiture e coordinamento delle lavorazioni.',
  alias: ['ristrutturazione cucina', 'cucina nuova', 'rifare cucina'],
  searchTerms: [
    'rifacimento cucina',
    'ristrutturazione cucina',
    'cucina nuova',
    'rifare cucina',
    'cucina chiavi in mano',
  ],
  ordine: 10,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Ristrutturazione cucina chiavi in mano' },
    { catSlug: 'impresa-edile', nome: 'Demolizioni e rimozioni' },
    { catSlug: 'impresa-edile', nome: 'Coordinamento lavori edili' },
  ],
},
{
  nome: 'Rifacimento facciata',
  slug: 'rifacimento-facciata',
  descrizione:
    'Rifacimento o ripristino della facciata con intonaci, rasature, finiture e protezioni.',
  alias: ['ristrutturazione facciata', 'lavori facciata', 'rifare facciata'],
  searchTerms: [
    'rifacimento facciata',
    'ristrutturazione facciata',
    'lavori facciata',
    'manutenzione facciata',
    'rifare facciata',
  ],
  ordine: 25,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Rifacimento facciata' },
    { catSlug: 'impresa-edile', nome: 'Intonaci e rasature' },
    { catSlug: 'impresa-edile', nome: 'Impermeabilizzazione facciata' },
  ],
},
{
  nome: 'Rifacimento balconi',
  slug: 'rifacimento-balconi',
  descrizione:
    'Rifacimento dei balconi con ripristino superfici, frontalini, impermeabilizzazione e finiture.',
  alias: ['ristrutturazione balconi', 'rifare balconi', 'balconi da sistemare'],
  searchTerms: [
    'rifacimento balconi',
    'ristrutturazione balconi',
    'rifare balconi',
    'balconi da sistemare',
    'ripristino balconi',
  ],
  ordine: 28,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Rifacimento balconi' },
    { catSlug: 'impresa-edile', nome: 'Demolizioni e rimozioni' },
  ],
},
{
  nome: 'Cappotto termico',
  slug: 'cappotto-termico',
  descrizione:
    'Installazione di cappotto termico per isolamento, protezione della facciata e riqualificazione energetica.',
  alias: ['isolamento facciata', 'cappotto esterno', 'coibentazione pareti'],
  searchTerms: [
    'cappotto termico',
    'isolamento facciata',
    'cappotto esterno',
    'coibentazione pareti',
    'riqualificazione energetica',
  ],
  ordine: 26,
  categorie: [{ slug: 'impresa-edile', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-edile', nome: 'Cappotto termico' },
    { catSlug: 'impresa-edile', nome: 'Intonaci e rasature' },
  ],
},
{
  nome: 'Montaggio mobili',
  slug: 'montaggio-mobili',
  descrizione:
    'Montaggio di mobili, arredi, armadi, complementi e piccoli elementi domestici.',
  alias: ['montare mobili', 'assemblaggio mobili', 'montaggio armadio', 'montaggio mobili ikea'],
  searchTerms: [
    'montaggio mobili',
    'montare mobili',
    'assemblaggio mobili',
    'montaggio armadio',
    'montaggio mobili ikea',
    'tuttofare mobili',
  ],
  ordine: 37,
  categorie: [{ slug: 'tuttofare', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'tuttofare', nome: 'Montaggio mobili' },
    { catSlug: 'tuttofare', nome: 'Montaggio mobili IKEA' },
  ],
},
{
  nome: 'Sigillatura bagno',
  slug: 'sigillatura-bagno',
  descrizione:
    'Sigillatura o rifacimento silicone per sanitari, vasca, doccia e zone umide del bagno.',
  alias: ['silicone bagno', 'rifare silicone bagno', 'sigillare doccia'],
  searchTerms: [
    'sigillatura bagno',
    'silicone bagno',
    'rifare silicone bagno',
    'sigillare doccia',
    'rifare silicone doccia',
  ],
  ordine: 8,
  categorie: [{ slug: 'tuttofare', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'tuttofare', nome: 'Sigillatura e stuccatura' }],
},
{
  nome: 'Appendere quadri e mensole',
  slug: 'appendere-quadri-mensole',
  descrizione:
    'Fissaggio di quadri, mensole, piccoli arredi, supporti e accessori domestici a parete.',
  alias: ['appendere mensole', 'montare mensola', 'appendere quadro', 'fissaggi a muro'],
  searchTerms: [
    'appendere quadri',
    'appendere mensole',
    'montare mensola',
    'appendere quadro',
    'fissaggi a muro',
  ],
  ordine: 104,
  categorie: [{ slug: 'tuttofare', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'tuttofare', nome: 'Appendere quadri e mensole' },
    { catSlug: 'tuttofare', nome: 'Piccoli fissaggi domestici' },
  ],
},
{
  nome: 'Piccole riparazioni domestiche',
  slug: 'piccole-riparazioni-domestiche',
  descrizione:
    'Piccole riparazioni e manutenzioni domestiche non specialistiche.',
  alias: ['piccoli lavori casa', 'riparazioni casa', 'manutenzione domestica'],
  searchTerms: [
    'piccole riparazioni domestiche',
    'piccoli lavori casa',
    'riparazioni casa',
    'manutenzione domestica',
    'tuttofare casa',
  ],
  ordine: 105,
  categorie: [{ slug: 'tuttofare', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'tuttofare', nome: 'Piccole riparazioni domestiche' }],
},
{
  nome: 'Pratica catastale',
  slug: 'pratica-catastale',
  descrizione:
    'Gestione di pratiche catastali, aggiornamenti, variazioni e documentazione tecnica collegata.',
  alias: ['catasto', 'variazione catastale', 'aggiornamento catastale'],
  searchTerms: [
    'pratica catastale',
    'catasto',
    'variazione catastale',
    'aggiornamento catastale',
    'geometra catasto',
  ],
  ordine: 106,
  categorie: [{ slug: 'geometra', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'geometra', nome: 'Pratica catastale' },
    { catSlug: 'geometra', nome: 'Variazione catastale' },
  ],
},
{
  nome: 'Pratica CILA',
  slug: 'pratica-cila',
  descrizione:
    'Gestione della pratica CILA per lavori edilizi di manutenzione straordinaria.',
  alias: ['fare cila', 'presentazione cila', 'cila ristrutturazione'],
  searchTerms: [
    'pratica cila',
    'fare cila',
    'presentazione cila',
    'cila ristrutturazione',
    'geometra cila',
  ],
  ordine: 41,
  categorie: [{ slug: 'geometra', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'geometra', nome: 'Pratica CILA' }],
},
{
  nome: 'Pratica SCIA',
  slug: 'pratica-scia',
  descrizione:
    'Gestione della pratica SCIA per interventi edilizi soggetti a segnalazione certificata.',
  alias: ['fare scia', 'presentazione scia', 'scia edilizia'],
  searchTerms: [
    'pratica scia',
    'fare scia',
    'presentazione scia',
    'scia edilizia',
    'geometra scia',
  ],
  ordine: 42,
  categorie: [{ slug: 'geometra', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'geometra', nome: 'Pratica SCIA' }],
},
{
  nome: 'Direzione lavori',
  slug: 'direzione-lavori',
  descrizione:
    'Coordinamento tecnico e controllo dell’esecuzione dei lavori in cantiere.',
  alias: ['direttore lavori', 'seguire cantiere', 'coordinamento lavori'],
  searchTerms: [
    'direzione lavori',
    'direttore lavori',
    'coordinamento lavori',
    'seguire cantiere',
    'direzione cantiere',
  ],
  ordine: 40,
  categorie: [{ slug: 'geometra', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'geometra', nome: 'Direzione lavori' }],
},
{
  nome: 'Progetto ristrutturazione',
  slug: 'progetto-ristrutturazione',
  descrizione:
    'Progettazione tecnica, distributiva e architettonica prima di una ristrutturazione.',
  alias: ['progetto casa', 'progettazione ristrutturazione', 'architetto ristrutturazione'],
  searchTerms: [
    'progetto ristrutturazione',
    'progettazione ristrutturazione',
    'architetto ristrutturazione',
    'progetto casa',
    'distribuzione spazi',
  ],
  ordine: 39,
  categorie: [{ slug: 'architetto', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'architetto', nome: 'Progetto ristrutturazione' },
    { catSlug: 'architetto', nome: 'Distribuzione spazi interni' },
  ],
},
{
  nome: 'Ampliamento casa',
  slug: 'ampliamento-casa',
  descrizione:
    'Progettazione di un ampliamento di casa esistente con nuove superfici o nuovi ambienti.',
  alias: ['allargare casa', 'aggiungere stanza', 'estensione casa'],
  searchTerms: [
    'ampliamento casa',
    'allargare casa',
    'estensione abitazione',
    'nuova stanza casa',
    'progetto ampliamento',
  ],
  ordine: 3,
  categorie: [{ slug: 'architetto', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'architetto', nome: 'Progetto ampliamento' }],
},
{
  nome: 'Progetto nuova costruzione',
  slug: 'progetto-nuova-costruzione',
  descrizione:
    'Progettazione architettonica di una nuova casa o nuova costruzione residenziale.',
  alias: ['progetto casa nuova', 'progettare casa', 'nuova abitazione'],
  searchTerms: [
    'progetto nuova costruzione',
    'progetto casa nuova',
    'progettare casa',
    'nuova abitazione',
    'architetto nuova casa',
  ],
  ordine: 107,
  categorie: [{ slug: 'architetto', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'architetto', nome: 'Progetto nuova costruzione' }],
},
{
  nome: 'Interior design',
  slug: 'interior-design',
  descrizione:
    'Progettazione estetica e funzionale degli spazi interni, con studio di arredi, materiali, colori e finiture.',
  alias: ['progetto interni', 'design interni', 'arredamento casa'],
  searchTerms: [
    'interior design',
    'progetto interni',
    'design interni',
    'arredamento casa',
    'scelta materiali',
  ],
  ordine: 108,
  categorie: [{ slug: 'interior-designer', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'interior-designer', nome: 'Progetto arredo interni' },
    { catSlug: 'interior-designer', nome: 'Scelta materiali e finiture' },
  ],
},
{
  nome: 'Home staging',
  slug: 'home-staging',
  descrizione:
    'Valorizzazione estetica di un immobile per vendita, affitto o presentazione commerciale.',
  alias: ['valorizzazione casa', 'preparare casa per vendita', 'home stager'],
  searchTerms: [
    'home staging',
    'valorizzazione casa',
    'preparare casa per vendita',
    'home stager',
  ],
  ordine: 109,
  categorie: [{ slug: 'interior-designer', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'interior-designer', nome: 'Home staging' }],
},
{
  nome: 'Consulenza arredamento',
  slug: 'consulenza-arredamento',
  descrizione:
    'Consulenza per scelta arredi, disposizione mobili, colori, materiali e stile degli ambienti.',
  alias: ['aiuto arredamento', 'consulente arredo', 'scelta mobili'],
  searchTerms: [
    'consulenza arredamento',
    'aiuto arredamento',
    'consulente arredo',
    'scelta mobili',
    'arredare casa',
  ],
  ordine: 110,
  categorie: [{ slug: 'interior-designer', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'interior-designer', nome: 'Consulenza arredamento' }],
},
{
  nome: 'Perizia strutturale',
  slug: 'perizia-strutturale',
  descrizione:
    'Valutazione tecnica di elementi strutturali, lesioni, solai, muri portanti o condizioni statiche.',
  alias: ['verifica strutturale', 'controllo struttura', 'perizia ingegnere'],
  searchTerms: [
    'perizia strutturale',
    'verifica strutturale',
    'controllo struttura',
    'muro portante',
    'lesioni strutturali',
  ],
  ordine: 111,
  categorie: [{ slug: 'ingegnere', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'ingegnere', nome: 'Perizia strutturale' },
    { catSlug: 'ingegnere', nome: 'Verifica strutturale' },
  ],
},
{
  nome: 'Certificazione energetica APE',
  slug: 'certificazione-energetica-ape',
  descrizione:
    'Rilascio dell’attestato di prestazione energetica per immobile.',
  alias: ['ape casa', 'attestato energetico', 'certificato energetico'],
  searchTerms: [
    'certificazione energetica ape',
    'ape casa',
    'attestato energetico',
    'certificazione energetica',
  ],
  ordine: 43,
  categorie: [{ slug: 'ingegnere', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'ingegnere', nome: 'Certificazione energetica APE' }],
},
{
  nome: 'Progetto impianti',
  slug: 'progetto-impianti',
  descrizione:
    'Progettazione tecnica di impianti civili o industriali con relazioni e documentazione necessaria.',
  alias: ['progettazione impianti', 'progetto impianto elettrico', 'progetto impianto termico'],
  searchTerms: [
    'progetto impianti',
    'progettazione impianti',
    'progetto impianto elettrico',
    'progetto impianto termico',
    'ingegnere impianti',
  ],
  ordine: 112,
  categorie: [{ slug: 'ingegnere', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'ingegnere', nome: 'Progetto impianti' }],
},
    
{
  nome: 'Tinteggiatura pareti',
  slug: 'tinteggiatura-pareti',
  descrizione:
    'Tinteggiatura di pareti interne con rinnovo colore e finitura.',
  alias: ['imbiancare pareti', 'pittura muri', 'verniciare pareti'],
  searchTerms: [
    'tinteggiatura pareti',
    'imbiancare pareti',
    'pittura muri interni',
    'verniciare pareti',
  ],
  ordine: 20,
  categorie: [{ slug: 'imbianchino', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'imbianchino', nome: 'Tinteggiatura pareti interne' }],
},
{
  nome: 'Posa piastrelle bagno',
  slug: 'posa-piastrelle-bagno',
  descrizione:
    'Posa o sostituzione di piastrelle e rivestimenti nel bagno.',
  alias: ['piastrelle bagno', 'rivestimento bagno', 'rifare piastrelle bagno'],
  searchTerms: [
    'posa piastrelle bagno',
    'piastrelle bagno',
    'rivestimento bagno',
    'rifare piastrelle bagno',
  ],
  ordine: 22,
  categorie: [{ slug: 'piastrellista', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'piastrellista', nome: 'Posa piastrelle bagno' },
    { catSlug: 'piastrellista', nome: 'Riparazione fughe e piastrelle' },
  ],
},
{
  nome: 'Posa pavimento',
  slug: 'posa-pavimento',
  descrizione:
    'Posa o sostituzione di pavimenti interni in gres, parquet o resina.',
  alias: ['rifare pavimento', 'cambio pavimento', 'nuovo pavimento'],
  searchTerms: [
    'posa pavimento',
    'rifare pavimento',
    'cambio pavimento',
    'nuovo pavimento',
    'pavimentista',
  ],
  ordine: 21,
  categorie: [{ slug: 'pavimentista', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'pavimentista', nome: 'Posa pavimento in gres' },
    { catSlug: 'pavimentista', nome: 'Posa parquet' },
    { catSlug: 'pavimentista', nome: 'Posa pavimento in resina' },
  ],
},
{
  nome: 'Installazione porte interne',
  slug: 'installazione-porte-interne',
  descrizione:
    'Installazione o sostituzione di porte interne in legno, laminato o altri materiali.',
  alias: ['montaggio porte interne', 'porte interne nuove', 'sostituzione porte interne'],
  searchTerms: [
    'installazione porte interne',
    'montaggio porte interne',
    'porte interne nuove',
    'sostituzione porte interne',
    'falegname porte',
  ],
  ordine: 94,
  categorie: [{ slug: 'falegname', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'falegname', nome: 'Installazione porte interne' }],
},
{
  nome: 'Sistemazione giardino',
  slug: 'sistemazione-giardino',
  descrizione:
    'Sistemazione e riordino di un giardino con manutenzione e ripristino del verde.',
  alias: ['giardino da sistemare', 'riqualificare giardino', 'rifare giardino'],
  searchTerms: [
    'sistemazione giardino',
    'giardino da sistemare',
    'riqualificare giardino',
    'rifare giardino',
    'manutenzione giardino',
  ],
  ordine: 33,
  categorie: [{ slug: 'giardiniere', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'giardiniere', nome: 'Manutenzione giardino' },
    { catSlug: 'giardiniere', nome: 'Progettazione giardino' },
  ],
},
{
  nome: 'Installazione antenna TV',
  slug: 'installazione-antenna-tv',
  descrizione:
    'Installazione o sostituzione di antenna TV per abitazioni, condomini o locali.',
  alias: ['antenna tv nuova', 'montaggio antenna tv', 'installare antenna'],
  searchTerms: [
    'installazione antenna TV',
    'antenna tv nuova',
    'montaggio antenna tv',
    'installare antenna',
    'antennista',
  ],
  ordine: 99,
  categorie: [{ slug: 'antennista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'antennista', nome: 'Installazione antenna TV' }],
},
{
  nome: 'Derattizzazione',
  slug: 'derattizzazione',
  descrizione:
    'Trattamento professionale contro topi e roditori in abitazioni, cantine, negozi o locali.',
  alias: ['topi in casa', 'eliminare topi', 'trattamento roditori'],
  searchTerms: [
    'derattizzazione',
    'topi in casa',
    'eliminare topi',
    'trattamento roditori',
    'disinfestazione topi',
  ],
  ordine: 65,
  categorie: [{ slug: 'disinfestatore', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'disinfestatore', nome: 'Derattizzazione' }],
},
{
  nome: 'Pulizia fine cantiere',
  slug: 'pulizia-fine-cantiere',
  descrizione:
    'Pulizia approfondita di ambienti dopo lavori edili o ristrutturazioni.',
  alias: ['pulizie fine cantiere', 'pulizia dopo lavori', 'pulizia post ristrutturazione'],
  searchTerms: [
    'pulizia fine cantiere',
    'pulizie fine cantiere',
    'pulizia dopo lavori',
    'pulizia post ristrutturazione',
  ],
  ordine: 47,
  categorie: [{ slug: 'pulitore-professionale', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'pulitore-professionale', nome: 'Pulizia fine cantiere' },
    { catSlug: 'pulitore-professionale', nome: 'Pulizia vetri e facciate' },
  ],
},
{
  nome: 'Trasloco appartamento',
  slug: 'trasloco-appartamento',
  descrizione:
    'Trasloco completo di appartamento con movimentazione, smontaggio e rimontaggio mobili.',
  alias: ['traslocare casa', 'trasloco casa', 'cambio casa'],
  searchTerms: [
    'trasloco appartamento',
    'traslocare casa',
    'trasloco casa',
    'cambio casa',
  ],
  ordine: 44,
  categorie: [{ slug: 'traslocatore', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'traslocatore', nome: 'Trasloco appartamento' },
    { catSlug: 'traslocatore', nome: 'Montaggio e smontaggio mobili' },
  ],
},
{
  nome: 'Rifacimento tetto',
  slug: 'rifacimento-tetto',
  descrizione:
    'Rifacimento completo o parziale del tetto con copertura, impermeabilizzazione e ripristini collegati.',
  alias: ['rifare tetto', 'tetto da rifare', 'ristrutturazione tetto'],
  searchTerms: [
    'rifacimento tetto',
    'rifare tetto',
    'tetto da rifare',
    'ristrutturazione tetto',
  ],
  ordine: 57,
  categorie: [{ slug: 'impresa-coperture', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'impresa-coperture', nome: 'Rifacimento tetto' }],
},
    
    {
  nome: 'Rifacimento impianto elettrico',
  slug: 'rifacimento-impianto-elettrico',
  descrizione:
    'Rifacimento completo o parziale dell’impianto elettrico domestico.',
  alias: ['rifare impianto elettrico', 'impianto elettrico nuovo', 'rifacimento elettrico casa'],
  searchTerms: [
    'rifacimento impianto elettrico',
    'rifare impianto elettrico',
    'impianto elettrico nuovo',
    'rifacimento elettrico casa',
  ],
  ordine: 15,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'elettricista', nome: 'Installazione impianto elettrico' },
    { catSlug: 'elettricista', nome: 'Messa a norma impianto elettrico' },
  ],
},
{
  nome: 'Sostituzione prese e interruttori',
  slug: 'sostituzione-prese-interruttori',
  descrizione:
    'Sostituzione di prese, placche, interruttori o piccoli componenti elettrici.',
  alias: ['cambiare presa', 'cambiare interruttore', 'presa rotta', 'interruttore rotto'],
  searchTerms: [
    'sostituzione prese',
    'sostituzione interruttori',
    'cambiare presa',
    'cambiare interruttore',
    'presa rotta',
    'interruttore rotto',
  ],
  ordine: 53,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Sostituzione prese e interruttori' }],
},
{
  nome: 'Messa a norma impianto elettrico',
  slug: 'messa-a-norma-impianto-elettrico',
  descrizione:
    'Adeguamento e messa a norma dell’impianto elettrico domestico o condominiale.',
  alias: ['impianto elettrico a norma', 'adeguamento impianto elettrico', 'certificazione impianto elettrico'],
  searchTerms: [
    'messa a norma impianto elettrico',
    'impianto elettrico a norma',
    'adeguamento impianto elettrico',
    'certificazione impianto elettrico',
  ],
  ordine: 54,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Messa a norma impianto elettrico' }],
},
{
  nome: 'Installazione quadro elettrico',
  slug: 'installazione-quadro-elettrico',
  descrizione:
    'Installazione o sostituzione del quadro elettrico domestico o condominiale.',
  alias: ['quadro elettrico nuovo', 'sostituzione quadro elettrico', 'rifare quadro elettrico'],
  searchTerms: [
    'installazione quadro elettrico',
    'sostituzione quadro elettrico',
    'quadro elettrico nuovo',
    'rifare quadro elettrico',
  ],
  ordine: 55,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Installazione quadro elettrico' }],
},
{
  nome: 'Installazione punti luce',
  slug: 'installazione-punti-luce',
  descrizione:
    'Installazione o spostamento di punti luce, lampade, plafoniere e collegamenti elettrici.',
  alias: ['nuovi punti luce', 'montaggio lampade', 'installare plafoniera', 'spostare punto luce'],
  searchTerms: [
    'installazione punti luce',
    'nuovi punti luce',
    'montaggio lampade',
    'installare plafoniera',
    'spostare punto luce',
  ],
  ordine: 81,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Installazione punti luce' }],
},
{
  nome: 'Riparazione guasto elettrico',
  slug: 'riparazione-guasto-elettrico',
  descrizione:
    'Ricerca e riparazione di guasti elettrici, corto circuiti, salvavita che scatta o prese non funzionanti.',
  alias: ['guasto elettrico', 'corto circuito', 'salvavita scatta', 'presa non funziona'],
  searchTerms: [
    'riparazione guasto elettrico',
    'guasto elettrico',
    'corto circuito',
    'salvavita scatta',
    'presa non funziona',
  ],
  ordine: 82,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Riparazione guasto elettrico' }],
},
{
  nome: 'Installazione salvavita',
  slug: 'installazione-salvavita',
  descrizione:
    'Installazione o sostituzione del salvavita e dei dispositivi di protezione elettrica.',
  alias: ['sostituzione salvavita', 'salvavita nuovo', 'differenziale elettrico'],
  searchTerms: [
    'installazione salvavita',
    'sostituzione salvavita',
    'salvavita nuovo',
    'differenziale elettrico',
  ],
  ordine: 83,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Installazione salvavita' }],
},
{
  nome: 'Installazione wallbox',
  slug: 'installazione-wallbox',
  descrizione:
    'Installazione di wallbox o caricatore domestico per auto elettrica.',
  alias: ['caricatore auto elettrica', 'colonnina auto casa', 'wallbox casa'],
  searchTerms: [
    'installazione wallbox',
    'caricatore auto elettrica',
    'colonnina auto casa',
    'wallbox casa',
  ],
  ordine: 56,
  categorie: [{ slug: 'elettricista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'elettricista', nome: 'Installazione wallbox' }],
},
    {
  nome: 'Cartongesso',
  slug: 'cartongesso',
  descrizione:
    'Realizzazione di pareti, contropareti o divisori in cartongesso.',
  alias: ['parete in cartongesso', 'lavori cartongesso', 'cartongesso casa'],
  searchTerms: [
    'cartongesso',
    'parete in cartongesso',
    'lavori cartongesso',
    'cartongesso casa',
    'divisorio cartongesso',
  ],
  ordine: 23,
  categorie: [{ slug: 'cartongessista', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'cartongessista', nome: 'Pareti in cartongesso' },
    { catSlug: 'cartongessista', nome: 'Contropareti in cartongesso' },
  ],
},
{
  nome: 'Controsoffitto',
  slug: 'controsoffitto',
  descrizione:
    'Realizzazione o rifacimento di controsoffitti tecnici o decorativi in cartongesso.',
  alias: ['fare controsoffitto', 'controsoffitto cartongesso', 'abbassamento soffitto'],
  searchTerms: [
    'controsoffitto',
    'fare controsoffitto',
    'controsoffitto cartongesso',
    'abbassamento soffitto',
    'soffitto in cartongesso',
  ],
  ordine: 24,
  categorie: [{ slug: 'cartongessista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'cartongessista', nome: 'Controsoffitti in cartongesso' }],
},
{
  nome: 'Velette e abbassamenti in cartongesso',
  slug: 'velette-abbassamenti-cartongesso',
  descrizione:
    'Realizzazione di velette, abbassamenti, gole luminose e dettagli decorativi in cartongesso.',
  alias: ['veletta cartongesso', 'abbassamento cartongesso', 'gola luminosa cartongesso'],
  searchTerms: [
    'velette cartongesso',
    'abbassamenti cartongesso',
    'veletta cartongesso',
    'gola luminosa cartongesso',
    'cartongesso decorativo',
  ],
  ordine: 79,
  categorie: [{ slug: 'cartongessista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'cartongessista', nome: 'Velette e abbassamenti' }],
},
{
  nome: 'Riparazione cartongesso',
  slug: 'riparazione-cartongesso',
  descrizione:
    'Riparazione di pareti, controsoffitti o elementi in cartongesso danneggiati.',
  alias: ['cartongesso rotto', 'riparare cartongesso', 'sistemare cartongesso'],
  searchTerms: [
    'riparazione cartongesso',
    'cartongesso rotto',
    'riparare cartongesso',
    'sistemare cartongesso',
    'buco cartongesso',
  ],
  ordine: 80,
  categorie: [{ slug: 'cartongessista', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'cartongessista', nome: 'Riparazioni cartongesso' }],
},
    {
  nome: 'Demolizione muro',
  slug: 'demolizione-muro',
  descrizione:
    'Demolizione di muri, pareti o tramezzi non strutturali per apertura spazi e ridistribuzione interna.',
  alias: ['abbattere muro', 'demolire parete', 'rimozione tramezzo', 'buttare giù muro'],
  searchTerms: [
    'demolizione muro',
    'abbattere muro',
    'demolire parete',
    'rimozione tramezzo',
    'buttare giù muro',
  ],
  ordine: 11,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'muratore', nome: 'Demolizioni e rimozioni leggere' }],
},
{
  nome: 'Costruzione tramezzo',
  slug: 'costruzione-tramezzo',
  descrizione:
    'Costruzione di un nuovo tramezzo o parete divisoria interna in muratura.',
  alias: ['realizzazione tramezzo', 'fare tramezzo', 'nuova parete interna'],
  searchTerms: [
    'costruzione tramezzo',
    'realizzazione tramezzo',
    'fare tramezzo',
    'parete divisoria casa',
    'nuova parete interna',
  ],
  ordine: 12,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'muratore', nome: 'Costruzione muri e tramezze' },
    { catSlug: 'muratore', nome: 'Posa mattoni e blocchi' },
  ],
},
{
  nome: 'Apertura porta o finestra',
  slug: 'apertura-porta-finestra',
  descrizione:
    'Apertura o modifica di un vano per porta o finestra in muratura non strutturale.',
  alias: ['aprire porta muro', 'aprire finestra muro', 'nuova apertura muro'],
  searchTerms: [
    'apertura porta o finestra',
    'aprire porta muro',
    'aprire finestra muro',
    'nuova apertura parete',
    'nuova apertura muro',
  ],
  ordine: 13,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'muratore', nome: 'Apertura vani porta e finestra' }],
},
{
  nome: 'Intonaci e rasature',
  slug: 'intonaci-e-rasature',
  descrizione:
    'Ripristino e finitura di intonaci e rasature su pareti interne o esterne.',
  alias: ['rasare muri', 'rifare intonaco', 'intonaco pareti', 'rasatura pareti'],
  searchTerms: [
    'intonaci e rasature',
    'rasare muri',
    'rifare intonaco',
    'intonaco pareti',
    'rasatura pareti',
  ],
  ordine: 19,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'muratore', nome: 'Intonaci e rasature' },
    { catSlug: 'muratore', nome: 'Riparazione crepe e lesioni' },
  ],
},
{
  nome: 'Rifacimento frontalini balconi',
  slug: 'rifacimento-frontalini-balconi',
  descrizione:
    'Ripristino di frontalini balconi ammalorati con rasature, riprese murarie e finiture protettive.',
  alias: ['frontalini balconi', 'frontalino balcone', 'ripristino frontalini'],
  searchTerms: [
    'rifacimento frontalini balconi',
    'frontalini balconi',
    'frontalino balcone',
    'ripristino frontalini',
  ],
  ordine: 29,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [{ catSlug: 'muratore', nome: 'Ripristino frontalini' }],
},
{
  nome: 'Riparazione muro',
  slug: 'riparazione-muro',
  descrizione:
    'Riparazione di crepe, porzioni ammalorate o piccoli danni murari.',
  alias: ['riparare muro', 'crepa nel muro', 'muro da sistemare'],
  searchTerms: [
    'riparazione muro',
    'riparare muro',
    'crepa nel muro',
    'muro da sistemare',
  ],
  ordine: 34,
  categorie: [{ slug: 'muratore', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'muratore', nome: 'Piccola muratura' },
    { catSlug: 'muratore', nome: 'Riparazione crepe e lesioni' },
  ],
},
  {
    nome: 'Sostituzione vetro rotto',
    slug: 'sostituzione-vetro-rotto',
    descrizione:
      'Sostituzione di vetri rotti, vetrocamera o elementi vetrati di finestre, porte e serramenti.',
    alias: ['vetro rotto', 'cambio vetro', 'sostituire vetro finestra', 'vetrocamera rotta'],
    searchTerms: [
      'sostituzione vetro rotto',
      'vetro rotto',
      'cambio vetro',
      'sostituire vetro finestra',
      'vetrocamera rotta',
      'doppio vetro rotto',
    ],
    ordine: 60,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [
      { catSlug: 'serramentista-vetraio', nome: 'Sostituzione vetro rotto' },
      { catSlug: 'serramentista-vetraio', nome: 'Sostituzione vetrocamera' },
    ],
  },
  {
    nome: 'Installazione infissi',
    slug: 'installazione-infissi',
    descrizione: 'Installazione o sostituzione di infissi, finestre e serramenti esterni.',
    alias: ['cambio infissi', 'finestre nuove', 'sostituzione finestre', 'installazione finestre'],
    searchTerms: [
      'installazione infissi',
      'cambio infissi',
      'finestre nuove',
      'sostituzione finestre',
      'installazione finestre',
      'serramenti nuovi',
    ],
    ordine: 61,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [
      { catSlug: 'serramentista-vetraio', nome: 'Installazione infissi' },
      { catSlug: 'serramentista-vetraio', nome: 'Installazione finestre' },
    ],
  },
  {
    nome: 'Sostituzione vetrocamera',
    slug: 'sostituzione-vetrocamera',
    descrizione:
      'Sostituzione di vetrocamera, doppio vetro o vetro isolante danneggiato o appannato.',
    alias: [
      'cambio vetrocamera',
      'doppio vetro appannato',
      'vetrocamera appannata',
      'sostituire doppio vetro',
    ],
    searchTerms: [
      'sostituzione vetrocamera',
      'cambio vetrocamera',
      'doppio vetro appannato',
      'vetrocamera appannata',
      'vetro camera rotto',
    ],
    ordine: 68,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'serramentista-vetraio', nome: 'Sostituzione vetrocamera' }],
  },
  {
    nome: 'Riparazione serramenti',
    slug: 'riparazione-serramenti',
    descrizione:
      'Riparazione di serramenti, finestre, ante, cerniere, chiusure e meccanismi di apertura.',
    alias: ['serramento rotto', 'finestra che non chiude', 'riparare finestra', 'riparare infisso'],
    searchTerms: [
      'riparazione serramenti',
      'serramento rotto',
      'finestra che non chiude',
      'riparare finestra',
      'riparare infisso',
    ],
    ordine: 69,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'serramentista-vetraio', nome: 'Riparazione serramenti' }],
  },
  {
    nome: 'Regolazione finestre e porte finestre',
    slug: 'regolazione-finestre-porte-finestre',
    descrizione:
      'Regolazione di finestre, porte finestre e serramenti che chiudono male o sfregano.',
    alias: [
      'finestra che chiude male',
      'porta finestra bloccata',
      'regolare finestra',
      'regolare serramento',
    ],
    searchTerms: [
      'regolazione finestre',
      'regolazione porte finestre',
      'finestra che chiude male',
      'porta finestra bloccata',
      'regolare serramento',
    ],
    ordine: 70,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [
      {
        catSlug: 'serramentista-vetraio',
        nome: 'Regolazione finestre e porte finestre',
      },
    ],
  },
  {
    nome: 'Installazione zanzariere',
    slug: 'installazione-zanzariere',
    descrizione:
      'Installazione o sostituzione di zanzariere per finestre, porte finestre e balconi.',
    alias: ['montaggio zanzariere', 'zanzariere nuove', 'sostituzione zanzariere'],
    searchTerms: [
      'installazione zanzariere',
      'montaggio zanzariere',
      'zanzariere nuove',
      'sostituzione zanzariere',
    ],
    ordine: 71,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'serramentista-vetraio', nome: 'Installazione zanzariere' }],
  },
  {
    nome: 'Sostituzione tapparelle',
    slug: 'sostituzione-tapparelle',
    descrizione:
      'Sostituzione di tapparelle, avvolgibili e componenti collegati al serramento.',
    alias: ['cambio tapparelle', 'tapparella nuova', 'sostituire avvolgibile'],
    searchTerms: [
      'sostituzione tapparelle',
      'cambio tapparelle',
      'tapparella nuova',
      'sostituire avvolgibile',
      'avvolgibile nuovo',
    ],
    ordine: 72,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'serramentista-vetraio', nome: 'Sostituzione tapparelle' }],
  },
  {
    nome: 'Riparazione tapparelle',
    slug: 'riparazione-tapparelle',
    descrizione:
      'Riparazione di tapparelle bloccate, cinghie, rulli, guide e piccoli componenti.',
    alias: [
      'tapparella bloccata',
      'tapparella rotta',
      'cinghia tapparella rotta',
      'riparare avvolgibile',
    ],
    searchTerms: [
      'riparazione tapparelle',
      'tapparella bloccata',
      'tapparella rotta',
      'cinghia tapparella rotta',
      'riparare avvolgibile',
    ],
    ordine: 73,
    categorie: [{ slug: 'serramentista-vetraio', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'serramentista-vetraio', nome: 'Riparazione tapparelle' }],
  },
  {
    nome: 'Sostituzione sanitari',
    slug: 'sostituzione-sanitari',
    descrizione: 'Sostituzione di wc, bidet, lavabo o altri sanitari con nuovi elementi.',
    alias: ['cambio sanitari', 'cambiare wc', 'cambio lavabo', 'sostituire bidet'],
    searchTerms: [
      'sostituzione sanitari',
      'cambio sanitari',
      'cambio wc',
      'cambio lavabo',
      'sostituire bidet',
    ],
    ordine: 5,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Installazione sanitari' }],
  },
  {
    nome: 'Sostituzione vasca o doccia',
    slug: 'sostituzione-vasca-doccia',
    descrizione:
      'Sostituzione di una vasca o di una doccia con adattamenti idraulici locali.',
    alias: ['cambio vasca', 'cambio doccia', 'vasca a doccia', 'sostituzione doccia'],
    searchTerms: [
      'sostituzione vasca o doccia',
      'sostituzione doccia',
      'sostituzione vasca',
      'vasca a doccia',
      'cambio doccia',
    ],
    ordine: 6,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Sostituzione vasca o doccia' }],
  },
  {
    nome: 'Installazione box doccia',
    slug: 'installazione-box-doccia',
    descrizione: 'Installazione o sostituzione del box doccia con fissaggio e sigillatura.',
    alias: ['montaggio box doccia', 'box doccia nuovo', 'sostituzione box doccia'],
    searchTerms: [
      'installazione box doccia',
      'montaggio box doccia',
      'box doccia nuovo',
      'sostituzione box doccia',
    ],
    ordine: 7,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Installazione box doccia' }],
  },
  {
    nome: 'Riparazione scarico wc',
    slug: 'riparazione-scarico-wc',
    descrizione: 'Riparazione di scarico wc otturato, lento o malfunzionante.',
    alias: ['scarico wc otturato', 'wc che non scarica', 'riparazione scarico bagno'],
    searchTerms: [
      'riparazione scarico wc',
      'scarico wc otturato',
      'wc che non scarica',
      'scarico bagno lento',
    ],
    ordine: 9,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [
      { catSlug: 'idraulico', nome: 'Riparazione scarico wc' },
      { catSlug: 'idraulico', nome: 'Scarichi intasati' },
    ],
  },
  {
    nome: 'Rifacimento impianto idraulico',
    slug: 'rifacimento-impianto-idraulico',
    descrizione:
      'Rifacimento completo o parziale dell’impianto idraulico con carichi, scarichi e collegamenti.',
    alias: ['rifare impianto idraulico', 'impianto idraulico nuovo', 'rifare tubi acqua'],
    searchTerms: [
      'rifacimento impianto idraulico',
      'rifare impianto idraulico',
      'impianto idraulico nuovo',
      'rifare tubi acqua',
    ],
    ordine: 16,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Installazione impianto idraulico' }],
  },
  {
    nome: 'Sostituzione rubinetto',
    slug: 'sostituzione-rubinetto',
    descrizione: 'Sostituzione di rubinetto o miscelatore in bagno, cucina o lavanderia.',
    alias: ['cambio rubinetto', 'miscelatore nuovo', 'rubinetto bagno'],
    searchTerms: [
      'sostituzione rubinetto',
      'cambio rubinetto',
      'miscelatore nuovo',
      'rubinetto bagno',
    ],
    ordine: 35,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Sostituzione rubinetto' }],
  },
  {
    nome: 'Riparazione perdita acqua',
    slug: 'riparazione-perdita-acqua',
    descrizione:
      'Riparazione di perdite da tubazioni, rubinetti, sanitari o collegamenti idraulici.',
    alias: ['perdita acqua', 'perdita idrica', 'tubo che perde', 'perdita bagno'],
    searchTerms: [
      'riparazione perdita acqua',
      'perdita acqua',
      'perdita idrica',
      'tubo che perde',
      'perdita bagno',
    ],
    ordine: 48,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Riparazione perdita acqua' }],
  },
  {
    nome: 'Scarico intasato',
    slug: 'scarico-intasato',
    descrizione: 'Disostruzione di scarichi intasati in bagno, cucina o lavanderia.',
    alias: ['lavandino intasato', 'scarico otturato', 'tubo intasato'],
    searchTerms: [
      'scarico intasato',
      'lavandino intasato',
      'scarico otturato',
      'tubo intasato',
    ],
    ordine: 49,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Scarichi intasati' }],
  },
  {
    nome: 'Sostituzione boiler o scaldacqua',
    slug: 'sostituzione-boiler-scaldacqua',
    descrizione: 'Sostituzione o installazione di boiler, scaldacqua elettrico o a gas.',
    alias: ['cambio boiler', 'cambio scaldacqua', 'scaldabagno nuovo'],
    searchTerms: [
      'sostituzione boiler',
      'sostituzione scaldacqua',
      'cambio boiler',
      'scaldabagno nuovo',
    ],
    ordine: 52,
    categorie: [{ slug: 'idraulico', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'idraulico', nome: 'Sostituzione boiler o scaldacqua' }],
  },
  {
    nome: 'Sostituzione serratura',
    slug: 'sostituzione-serratura',
    descrizione:
      'Sostituzione o cambio serratura per porta, cancello, portone o accesso di servizio.',
    alias: ['cambio serratura', 'serratura da sostituire', 'nuova serratura'],
    searchTerms: [
      'sostituzione serratura',
      'cambio serratura',
      'serratura da sostituire',
      'nuova serratura',
      'fabbro serratura',
    ],
    ordine: 38,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Sostituzione serratura' }],
  },
  {
    nome: 'Riparazione serratura',
    slug: 'riparazione-serratura',
    descrizione:
      'Riparazione di serrature dure, bloccate, danneggiate o malfunzionanti.',
    alias: ['serratura bloccata', 'serratura rotta', 'riparare serratura'],
    searchTerms: [
      'riparazione serratura',
      'serratura bloccata',
      'serratura rotta',
      'riparare serratura',
    ],
    ordine: 74,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Riparazione serratura' }],
  },
  {
    nome: 'Apertura porta bloccata',
    slug: 'apertura-porta-bloccata',
    descrizione:
      'Apertura di porte bloccate, chiuse accidentalmente o con chiave spezzata nella serratura.',
    alias: ['porta bloccata', 'aprire porta', 'chiave spezzata', 'porta chiusa fuori'],
    searchTerms: [
      'apertura porta bloccata',
      'porta bloccata',
      'aprire porta',
      'chiave spezzata',
      'fabbro apertura porta',
    ],
    ordine: 75,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Apertura porta bloccata' }],
  },
  {
    nome: 'Installazione cancello',
    slug: 'installazione-cancello',
    descrizione:
      'Installazione di cancelli pedonali o carrabili, anche con strutture metalliche su misura.',
    alias: ['cancello nuovo', 'montaggio cancello', 'installare cancello'],
    searchTerms: [
      'installazione cancello',
      'cancello nuovo',
      'montaggio cancello',
      'installare cancello',
    ],
    ordine: 76,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Installazione cancello' }],
  },
  {
    nome: 'Riparazione cancello automatico',
    slug: 'riparazione-cancello-automatico',
    descrizione:
      'Riparazione di cancelli automatici, automazioni, componenti metallici e meccanismi di apertura.',
    alias: ['cancello automatico rotto', 'automazione cancello', 'cancello bloccato'],
    searchTerms: [
      'riparazione cancello automatico',
      'cancello automatico rotto',
      'automazione cancello',
      'cancello bloccato',
    ],
    ordine: 62,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Riparazione cancello automatico' }],
  },
  {
    nome: 'Installazione inferriate',
    slug: 'installazione-inferriate',
    descrizione:
      'Installazione di inferriate, grate di sicurezza e protezioni metalliche per finestre o accessi.',
    alias: ['grate di sicurezza', 'inferriata finestra', 'montaggio inferriate'],
    searchTerms: [
      'installazione inferriate',
      'grate di sicurezza',
      'inferriata finestra',
      'montaggio inferriate',
    ],
    ordine: 77,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Installazione inferriate' }],
  },
  {
    nome: 'Installazione recinzione',
    slug: 'installazione-recinzione',
    descrizione:
      'Installazione di recinzioni, reti, cancelli pedonali o delimitazioni esterne.',
    alias: ['recinzione giardino', 'rete recinzione', 'chiudere terreno'],
    searchTerms: [
      'installazione recinzione',
      'recinzione giardino',
      'rete recinzione',
      'chiudere terreno',
    ],
    ordine: 63,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Installazione recinzione' }],
  },
  {
    nome: 'Ripristino ringhiere balconi',
    slug: 'ripristino-ringhiere-balconi',
    descrizione:
      'Ripristino, riparazione o messa in sicurezza di ringhiere e parapetti dei balconi.',
    alias: ['ringhiera balcone', 'parapetto balcone', 'riparare ringhiere balconi'],
    searchTerms: [
      'ripristino ringhiere balconi',
      'ringhiera balcone',
      'parapetto balcone',
      'riparare ringhiere balconi',
    ],
    ordine: 30,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Riparazione ringhiere e parapetti' }],
  },
  {
    nome: 'Realizzazione ringhiere e parapetti',
    slug: 'realizzazione-ringhiere-parapetti',
    descrizione:
      'Realizzazione e posa di ringhiere, parapetti e protezioni metalliche su misura.',
    alias: ['ringhiera nuova', 'parapetto nuovo', 'ringhiere su misura'],
    searchTerms: [
      'realizzazione ringhiere',
      'realizzazione parapetti',
      'ringhiera nuova',
      'parapetto nuovo',
      'ringhiere su misura',
    ],
    ordine: 78,
    categorie: [{ slug: 'fabbro', isPrimary: true, priorita: 1 }],
    servizi: [{ catSlug: 'fabbro', nome: 'Realizzazione ringhiere e parapetti' }],
  },
  {
  nome: 'Realizzazione piscina',
  slug: 'realizzazione-piscina',
  descrizione:
    'Realizzazione di una nuova piscina privata interrata o fuori terra.',
  alias: ['costruzione piscina', 'fare piscina', 'piscina nuova'],
  searchTerms: [
    'realizzazione piscina',
    'costruzione piscina',
    'fare piscina',
    'piscina nuova',
  ],
  ordine: 113,
  categorie: [{ slug: 'impresa-piscine', isPrimary: true, priorita: 1 }],
  servizi: [
    { catSlug: 'impresa-piscine', nome: 'Realizzazione piscine interrate' },
    { catSlug: 'impresa-piscine', nome: 'Realizzazione piscine fuori terra' },
  ],
}
]

export const taxonomy: SettoreSeed[] = settoriData.map((settore) => ({
  ...settore,
  categorie: categorieData
    .filter((categoria) => categoria.settoreSlug === settore.slug)
    .map(({ settoreSlug: _settoreSlug, ...categoria }) => categoria),
}))